### ISSUE TITLE
Innovative Liquid Staking Protocol with Enhanced Rewards

### ISSUE THREAD

**Issue by huihzhao** [bnb-chain/community-contributions#49]
## Main Objectives/Goals:
Increase the liquid staking APY and provide additional benefits to users through enhanced MEV rewards, restaking, and liquid restaking. This will be a comprehensive, one-stop staking service that captures all the benefits from the ecosystem.
## Challenge Description:
Ethereum has proven the success of liquid staking with over [$46B](https://defillama.com/lsd) in TVL. As one of the top blockchains, BNBChain is proactively promoting staking and liquid staking, currently with < $1B in TVL. [MEV solution](https://www.bnbchain.org/en/blog/unlocking-the-potential-of-mev-on-bnb-chain-a-guide-for-builders-and-validators) is enabled and adopted by [30+ validators](https://github.com/bnb-chain/bsc-mev-info/tree/main/mainnet/validators), and [some builders](https://github.com/bnb-chain/bsc-mev-info/blob/main/mainnet/builders/blocksmith-ap.toml) are actively working in this direction. This is expected to increase the staking APY by 5% to 10%. 

At the same time, Restaking protocols like Karak and Binlayer have already launched on BNBChain, which will provide robust infrastructure for secure and efficient restaking of BNB. With these layers in place, BNBChain is fundamentally prepared to enhance and simplify the experience of liquid staking, restaking, and liquid restaking.                             
This innovative liquid staking layer will function as both the liquidity and aggregator layer for the entire staking service, streamlining and enhancing the overall staking experience.

**Comment by 9012Jessie** [comment]
It‘s not fully fulfilled yet.

**Comment by jasonrale** [comment]
# 🏦 [OutStake](https://outrun.gitbook.io/doc/outstake)

**_Not Only Native Yield Stake Protocol_**

**Outstake** is a protocol entirely built around **native yield tokens**, introducing the first **non-USD stablecoin model** tied to **native yield rates**. Compared to other yield token protocols in the market, such as **Pendle**, Outstake offers **greater flexibility, enhanced composability**, and provides **higher returns along with multiple sources of income**. The assets supported by Outstake form the foundational support for the Outrun ecosystem, providing a stable base for the entire system. Specifically, Outstake operates as follows:

**A New Staking Model Based on Native Yield Tokens:** Outstake adopts a unique design that allows users to control the native yield generated by their assets. Through Outstake, users can mint Principal Tokens **(PT)** by staking their assets, thereby unlocking liquidity for their staked assets and utilizing these tokens across a range of DeFi applications.

**Native Yield Stablecoin (also YT):** The value of the native yield stablecoin is directly tied to the **native yield rate**. The economic model built around it offers stakers higher income and multiple sources of revenue. It is highly composable, allowing developers to create new products around it, thereby enriching the Outrun ecosystem.

**Position Option Tokens:** These option tokens represent the right to redeem the **native yield token** at the end of its lock-up period. This option allows users to trade for a fixed interest rate without trading the **PT** itself, thereby enhancing capital efficiency.

## The difference between Outstake and Pendle

Currently, Pendle is the most popular native yield staking protocol on the market. Here’s a comparison of Outstake and Pendle, highlighting the advantages of Outstake and the problems it addresses:

1. **Token Types and Composability**

* **Pendle:** The minted Principal Tokens **(PT)** and Yield Tokens **(YT)** have an expiration date. **PT** and **YT** are not standard ERC20 tokens but are closer to NFTs (Non-fungible tokens). This limits the composability and use cases of assets on Pendle. Especially **YT**, whose value drops to zero at expiration, further restricts its usage.
* **Outstake:** The minted **PT** and **YT** are standard ERC20 tokens without an expiration date, allowing them to be traded on any decentralized exchange **(DEX)** and freely integrated into other DeFi protocols. This design enhances composability and flexibility. Additionally, Outstake’s **YT** can be seen as a stablecoin tied to the yield rate, enabling users to take long or short positions on the yield rate.

2. **Fixed Rate Yields**

* **Pendle:** The number of **PT** minted equals the amount of staked tokens, and **PT** suffer from a negative premium that decreases over time. Fixed-rate yields come from the negative premium of **PT**, i.e., **the loss incurred by stakers**. To obtain a fixed rate, users must purchase the corresponding **PT**. Due to the negative premium, early selling of **PT** results in losses, significantly reducing their practical value and making it difficult to integrate **PT** into other DeFi strategies.
* **Outstake:** The number of **PT** minted is related to the amount of **YT** minted and the redeemable value of **YT**, avoiding the negative premium of **PT**. Outstake introduces tradable **Position Options Token (POT)**, representing the redemption rights of native yield tokens at the end of the lock-up period. This allows users to obtain fixed-rate rights without trading **PT**, improving capital efficiency. The yield comes from demand exchanges, not from staking losses.

3. **Staking Duration**

* **Pendle:** The staking duration is determined by the protocol, and users cannot freely choose the staking period.
* **Outstake:** Users can freely select the staking duration, controlling the amount of **PT**  minted. The staking duration is abstracted as **POT**, making the position expiration time a tradable asset, further increasing flexibility.

4. **Yield Sources**

* **Pendle:** Pendle does not generate real external yields; its fixed-rate yields essentially come from the losses of staking users. Previously, Pendle’s high fixed-rate yields were driven by airdrop incentives from various restaking protocols, leading users to bear losses in exchange for airdrop rewards, which were short-lived.
* **Outstake:** Through the Outrun ecosystem, which supports multiple assets, Outstake creates a rich arbitrage market and multiple income sources. Users can earn native yields, fixed-rate returns from trading **POT**, and numerous arbitrage opportunities based on Outstake assets, enhancing the overall profitability and scalability of the protocol.

5. **Originality**

* **Pendle:** The **PT/YT** model used by Pendle is not original. It is derived from the fixed-rate lending model by **Element Finance**. Pendle expanded the use cases of the model created by **Element Finance**.
* **Outstake:** The **PT/YT** model used by Outstake is an entirely new and **original** model.

## Why choose Outstake?

1. **New Staking Model**

Outstake introduces a new staking model based on native yield tokens, allowing users to control the native yield generated by their assets.

Users can mint Staked Tokens to release liquidity for their staked assets and use them in various DeFi applications.

2. **Innovative Stablecoin Mechanism**

Outstake has designed a new algorithmic stablecoin tied to the yield rate, diverging from traditional USD-pegged stablecoins.

The economic model built around this stablecoin provides stakers with higher returns and multiple sources of income compared to traditional LSD protocols and yield token protocols.

3. **Powerful Composability**

The YT in Outrun offers high composability, allowing developers to build new products based on YT, thereby enriching the Outrun ecosystem.

4. **Position Options Token (POT)**

POT represents the redemption rights of native yield tokens at the end of the lock-up period. Through POT, users can trade for fixed-rate rights without directly trading PT itself, improving capital efficiency.

5. **Flash Loan Functionality**

Outstake offers flash loan functionality, providing stakers with higher yield potential from their native yield tokens.
